# Generated by Django 3.2.8 on 2021-10-23 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oracle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='datestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 22, 54, 23, 133916), null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='datestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 22, 54, 23, 133916), null=True),
        ),
    ]
