# Generated by Django 3.2.8 on 2021-10-23 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oracle', '0002_auto_20211023_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='datestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 23, 49, 58, 10375), null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='datestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 23, 49, 58, 14375), null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(default='clients/a.jpg', null=True, upload_to='clients'),
        ),
    ]
