# Generated by Django 3.2.8 on 2021-10-23 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oracle', '0004_auto_20211024_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='due',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='datestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 0, 46, 48, 855850), null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='datestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 0, 46, 48, 859849), null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Oracle.employee'),
        ),
    ]
